Repository beyond-sw-camp/be04-3rd-OmokNoonE-OmokFront, pull requests merged in 2024-03, with the labels that each got.

#4 [PR] Header
  OmokFront/src/App.vue
  OmokFront/src/assets/globals.css
  OmokFront/src/assets/img/1.png
  OmokFront/src/assets/img/1.svg
  OmokFront/src/assets/img/3.png
  OmokFront/src/assets/img/bookmark-1.svg
  OmokFront/src/assets/img/chat-alt-1.svg
  OmokFront/src/assets/img/darhboard.svg
  OmokFront/src/assets/img/date-range-1.svg
  OmokFront/src/assets/img/ellipse-47-1.svg
  OmokFront/src/assets/img/ellipse-48-1.svg
  OmokFront/src/assets/img/ellipse-48.svg
  OmokFront/src/assets/img/image-3-1.png
  OmokFront/src/assets/img/image-3.png
  OmokFront/src/assets/img/image.svg
  OmokFront/src/assets/img/line-1.svg
  OmokFront/src/assets/img/line-6.svg
  OmokFront/src/assets/img/package-box-alt.svg
  OmokFront/src/assets/img/polygon-1-1.svg
  OmokFront/src/assets/img/polygon-1.png
  OmokFront/src/assets/img/rectangle-4160-1.svg
  OmokFront/src/assets/img/rectangle-4160.svg
  OmokFront/src/assets/img/search-1.svg
  OmokFront/src/assets/img/sign-out-squre-1.svg
  OmokFront/src/assets/img/subtract-2.svg
  OmokFront/src/assets/img/subtract-3.svg
  OmokFront/src/assets/img/subtract-4.svg
  OmokFront/src/assets/img/subtract-5.svg
  OmokFront/src/assets/styleguide.css
  OmokFront/src/components/Header/HeaderAll.vue
  OmokFront/src/components/Header/HeaderMain/HeaderMain.vue
  OmokFront/src/components/Header/HeaderMain/SearchBar/SearchBar.vue
  OmokFront/src/components/Header/HeaderMain/SearchBar/default.vue
  OmokFront/src/components/Header/HeaderMain/TitleAndCategory/Category/Category.vue
  OmokFront/src/components/Header/HeaderMain/TitleAndCategory/Category/default.vue
  OmokFront/src/components/Header/HeaderMain/TitleAndCategory/Title/Title.vue
  OmokFront/src/components/Header/HeaderMain/TitleAndCategory/Title/default.vue
  OmokFront/src/components/Header/HeaderMain/TitleAndCategory/TitleAndCategory.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserBar.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserMenu/UserMenu.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserMenu/default.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserQuickMenu/UserQuickMenu.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserQuickMenu/default.vue
Labels: feature

#6 [PR] Omok Json Server json 파일 업로드
  OmokJsonServer/seeking_member_post_detail.json
  OmokJsonServer/seeking_member_post_list.json
Labels: feature

#7 [PR] 모집글 상세보기 구현
  OmokFront/src/App.vue
  OmokFront/src/assets/globals.css
  OmokFront/src/assets/img/2x.png
  OmokFront/src/assets/img/ellipse-583.svg
  OmokFront/src/assets/img/group.svg
  OmokFront/src/assets/img/image-2.svg
  OmokFront/src/assets/img/image-3.svg
  OmokFront/src/assets/img/line.svg
  OmokFront/src/assets/img/more.svg
  OmokFront/src/assets/img/rectangle-4248.svg
  OmokFront/src/assets/styleguide.css
  OmokFront/src/assets/폴더사라짐방지용
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostDetailAll.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/Apply/Apply.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostContents/PostContents.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostHeader/PostHeader.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/SeekingMemberPostMain.vue
  OmokFront/src/components/Sidebar/default.vue
Labels: feature, refactor

#11 [PR] 비회원 메인화면 구현
  OmokFront/src/assets/img/guestmain.png
  OmokFront/src/components/Section/GuestMainPage/GuestMainPage.vue
Labels: feature

#14 [PR]Seeking_member_post_list 화면 구현
  OmokFront/src/App.vue
  OmokFront/src/assets/img/bookmark-fill.svg
  OmokFront/src/assets/img/filter.svg
  OmokFront/src/assets/img/plus.svg
  OmokFront/src/assets/img/thumbnail.svg
  OmokFront/src/components/Section/SeekingMemberPost/list/SeekingMemberPostListMain.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionBody/SessionBody.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionContent/SessionContent.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionHeader/SessionHeaderDetail.vue
Labels: feature

#15 [PR] 모집글 상세보기 버튼 기능 추가
  OmokFront/src/assets/img/apply.svg
  OmokFront/src/assets/img/bookmark-selected.svg
  OmokFront/src/assets/img/bookmark-unselect.svg
  OmokFront/src/assets/img/post-default.svg
  OmokFront/src/assets/img/post-header-line.svg
  OmokFront/src/assets/img/profile-default-thumbnail.svg
  OmokFront/src/components/Header/HeaderMain/UserBar/UserQuickMenu/UserQuickMenu.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/Apply/Apply.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostContents/PostContents.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostHeader/PostHeader.vue
Labels: feature, Rename

#16 [PR] Guest login 화면 구현
  OmokFront/src/assets/img/sign-in-squre.png
  OmokFront/src/components/Header/HeaderMain/UserBar/GuestMenu/GuestMenu.vue
  OmokFront/src/components/Header/HeaderMain/UserBar/UserBar.vue
Labels: feature

#17 [PR] SeekingMemberPostList JSON 반영
  OmokFront/src/components/Section/SeekingMemberPost/list/SeekingMemberPostListMain.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionBody/SessionBody.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionContent/SessionContent.vue
  OmokFront/src/components/Section/SeekingMemberPost/list/SessionHeader/SessionHeaderDetail.vue
Labels: feature, refactor

#18 [PR] 모집글 상세보기 JSON 데이터
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostDetailAll.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostContents/PostContents.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/PostHeader/PostHeader.vue
  OmokFront/src/components/Section/SeekingMemberPost/Detail/SeekingMemberPostMain/SeekingMemberPostMain.vue
  OmokJsonServer/seeking_member_post_detail.json
Labels: bug, feature

#22 [PR] 모집글 상세 페이지 동적 전환 구현
  OmokFront/src/components/Section/SeekingPost/Detail/Apply.vue
  OmokFront/src/components/Section/SeekingPost/Detail/PostContents.vue
  OmokFront/src/components/Section/SeekingPost/Detail/PostHeader.vue
  OmokFront/src/components/Section/SeekingPost/Detail/SeekingPostUnion.vue
  OmokFront/src/views/SeekingPostDetailView.vue
Labels: feature, refactor

#24 [PR] AddSeekingPost 페이지 추가
  OmokFront/src/assets/img/close-round-duotone-1.svg
  OmokFront/src/assets/img/date-range-2.svg
  OmokFront/src/assets/img/line-18.svg
  OmokFront/src/assets/img/line-24-4.svg
  OmokFront/src/assets/img/line-24.svg
  OmokFront/src/assets/img/mdi-menu-down-1.svg
  OmokFront/src/assets/img/mdi-menu-down.svg
  OmokFront/src/assets/img/rectangle-4248.svg
  OmokFront/src/assets/img/writing-detail.svg
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostContent.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostDetail.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostHeader.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostUnion.vue
  OmokFront/src/components/Section/SeekingPost/List/ListContent.vue
  OmokFront/src/router/router.js
  OmokFront/src/views/AddSeekingPostView.vue
Labels: feature

#25 [PR] 모집글 작성 동적 페이지 구현
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostContent.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostDetail.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostHeader.vue
  OmokFront/src/components/Section/AddSeekingPost/AddSeekingPostUnion.vue
  OmokFront/src/components/Section/SeekingPost/List/ListContent.vue
  OmokFront/src/views/AddSeekingPostView.vue
Labels: feature, refactor

#27 [PR] 카테고리 검색(모집글), 자동완성 추가
  OmokFront/src/components/Header/SearchBar.vue
Labels: feature

#29 [PR] 모집글 목록 페이징 처리 (기능만)
  OmokFront/src/components/Section/SeekingPost/List/ListBody.vue
Labels: feature

#30 [PR] 모집글 작성 페이지 기능 추가
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostContent.vue
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostDetail.vue
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostHeader.vue
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostUnion.vue
Labels: feature, remove

#31 [PR] 모집글 목록 페이징 버튼 커서 변형 처리
  OmokFront/src/components/Section/SeekingPost/List/ListBody.vue
Labels: refactor

#32 [PR] 모집글 상세보기 종료 CSS 변경
  OmokFront/src/components/Section/SeekingPost/Detail/PostHeader.vue
Labels: refactor

#33 [PR] 헤더 검색 카테고리 기능 추가
  OmokFront/src/components/Header/SearchBar.vue
Labels: bug, feature

#34 [PR] 모집글 작성 시 모집글 목록에서 확인 가능
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostDetail.vue
  OmokFront/src/components/Section/SeekingPost/Add/AddSeekingPostUnion.vue
  OmokFront/src/views/SeekingPostListView.vue
Labels: feature
